# Generated by Django 5.2.4 on 2025-07-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerequest',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imagerequest',
            name='process',
            field=models.CharField(blank=True, help_text='Process status or worker identifier', max_length=32, null=True),
        ),
    ]
